### ISSUE TITLE
Test is failing on initial commits

### ISSUE THREAD

**Issue by moorepants** [conda-forge/yeadon-feedstock#1]
This worked in staged recipes, now getting:

```
+ source /opt/conda/bin/activate /feedstock_root/build_artefacts/recipe_root_1485800624137/_t_env
+ /bin/bash -x -e /feedstock_root/build_artefacts/recipe_root_1485800624137/test_tmp/run_test.sh
+ bash test.sh
  File "<stdin>", line 1
    upload_or_check_non_existence /recipe_root conda-forge --channel=main || exit 1
    ^
IndentationError: unexpected indent
  File "<stdin>", line 2
    set -x
    ^
IndentationError: unexpected indent
TESTS FAILED: yeadon-1.3.0-py27_0

./ci_support/run_docker_build.sh returned exit code 1
```

**Comment by ocefpaf** [comment]
I found the reason. Somehow the tests are causing that failure! Now I am looking for a proper fix that does not exclude the tests. Hold on a little more...

**Comment by ocefpaf** [comment]
When you are doing,

```shell
CMD="$PYTHON import_test.py"
DISPLAY=localhost:1.0 xvfb-run -a bash -c $CMD
```

This enters a python interpreter in my docker image and waits for user input. Do you need that test since you do run them again in https://github.com/conda-forge/yeadon-feedstock/blob/master/recipe/meta.yaml#L40-L41 ?

(The hint to find that was the Python indentation error in a bash script! That made no sense at first but now I see the rest of the build script was being piped to this python interpreter.)

See run `#2` and run `#3`, one with that test and another without: https://circleci.com/gh/ocefpaf/yeadon-feedstock

PS: Sending a PR with run `#2` for you now.

**Comment by moorepants** [comment]
I couldn't figure out how to run a script that imports mayavi on linux. That's why I have this code. See this recommendation: https://github.com/conda-forge/mayavi-feedstock/issues/7

**Comment by moorepants** [comment]
I've removed the mayavi as a hard dependency. So this can be closed.
